net:
  bindIpAll: true
  port: 27017
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
security:
  keyFile: /etc/mongo-keyfile
sharding:
  configDB: configReplSet/configsvr01:27017,configsvr02:27017,configsvr03:27017
