storage:
  dbPath: /data/db
net:
  bindIpAll: true
  port: 27018
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
security:
  authorization: enabled
  keyFile: /etc/mongo-keyfile
sharding:
  clusterRole: shardsvr
